### ISSUE TITLE
Cawley, WA missing from locality_bdys_display in the Admin Bdys Postgres dump

### ISSUE THREAD

**Issue by iag-hugh** [minus34/gnaf-loader#22]

**Comment by iag-hugh** [comment]
Issue fixed, new dump file uploaded to AWS

**Comment by keithamoss** [comment]
Was this a problem in gnaf-loader or upstream? :)

**Comment by minus34** [comment]
The issue was with the iag-geo/psma-admin-bdys process, which I run after gnaf-loader to finalise the Admin Bdys PG dump file.

Due to the fiddly logic to clean localities along the coastline - if a locality MBR centroid falls outside the locality, it can fail to be added to the display table. These are manually fixed. Any new errors are flagged at the end of the psma-admin-bdys process. I missed Cawley in the list due to lack of coffee!

The locality_bdys table generated by gnaf-loader has no errors.

**Comment by keithamoss** [comment]
Good to hear - and now I know you have a boundaries cleaning script that I'm going to be making a lot of use of.
